[build]
  command = "npm install && npx @11ty/eleventy"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://herocleanersllc.com/*"
  to = "https://theherocleaners.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.herocleanersllc.com/*"
  to = "https://theherocleaners.com/:splat"
  status = 301
  force = true
